import "./globals.css";
import SessionWrapper from "./components/sessionWrapper";
import Navbar from "./components/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          <Navbar />
        {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
